import { test, expect } from "@playwright/test";
test("Automate Decathlon", async ({page}) => {
    await page.goto("https://www.decathlon.in/")
    expect(page.locator('[enterkeyhint="search"]')).toBeVisible()
    let product = "shoes"
    await page.locator('[enterkeyhint="search"]').fill(product)
    await page.locator('[enterkeyhint="search"]').press("Enter")
    let pageTitle = await page.title()
    await page.waitForLoadState('domcontentloaded')
    console.log("The Title of the page is:", pageTitle)
    expect(page.title(), "Search | Shoes")
    await page.locator('[data-test-id="title:Sport"]').click()
    await page.locator('[data-test-id="checkbox-wrapper"]').first().click()
    await page.locator('[data-test-id="title:Gender"]').click()
    await page.locator('[data-test-id="checkbox-container"]').first().click()
    await page.locator('[data-test-id="title:Size"]').click()
    await page.locator('//span[text()="Uk 10.5 - eu 45"]').first().click()
    await page.locator('//span[text()="Most relevant"]').click()
    await page.locator('//span[text()="Price (high → low) "]').click()
    await page.locator('//span[text()="Kalenji"]').first().click()
    await page.locator('[class="dy-lb-close"]').click()
    await page.locator('[aria-label="Select Men Running Shoes Superior Grip Cushioned Upto 20km/week, Jogflow 190.1 - Black"]').first().click()
    await page.locator('[aria-label="Select size 10.5"]').click()
    await page.locator('[data-test-id="button-children"]').click()
    await page.locator('[data-test-id="header-desktop:cart-icon"]').click()
    const cartValue = await page.locator('[classname="font-semibold"]').nth(1).textContent()
    console.log("The Total Cart Value is : ", cartValue)
    await page.screenshot()
})