import { expect, test } from "@playwright/test";

test("Create Lead in Leaftaps", async ({ page }) => {
    await page.goto("https://leaftaps.com/opentaps/control/main")
    await page.getByRole("textbox", {name:"USERNAME"}).fill("democsr2")
    await page.getByRole("textbox", {name:"PASSWORD"}).fill("crmsfa")
    await page.getByRole("button", {name:"LOGIN"}).click()
    await page.locator('#label').click()
    await page.getByRole("link", {name:"Leads"}).click()
    await page.getByRole("link", {name:"Create Lead"}).click()
    let cname = "Geetha Pathology Lab"
    let fname = "Naveen"
    let lname = "K"
    await page.locator('#createLeadForm_companyName').fill(cname)
    await page.locator('#createLeadForm_firstName').fill(fname)
    await page.locator('#createLeadForm_lastName').fill(lname)
    await page.locator('//input[@name="personalTitle"]').fill("Mr. ")
    await page.locator('//input[@name="generalProfTitle"]').fill("MBBS")
    await page.locator("#createLeadForm_departmentName").fill("Pathology")
    await page.locator('[id="createLeadForm_annualRevenue"]').fill("15,00,000 LPA")
    await page.locator('#createLeadForm_primaryPhoneCountryCode').fill("+91")
    await page.locator('#createLeadForm_primaryPhoneNumber').fill("9876543210")
    await page.locator(".smallSubmit").click()
    let companyName = await page.locator('#viewLead_companyName_sp').textContent()
    let firstName = await page.locator('#viewLead_firstName_sp').textContent()
    let lastName = await page.locator('#viewLead_lastName_sp').textContent()
    let status = await page.locator('#viewLead_statusId_sp').textContent()
    console.log("Company Name: " + companyName)
    console.log("First Name: " + firstName)
    console.log("Last Name: " + lastName)
    console.log("Status: " + status)
    console.log("The Status of the Lead Mr. " + firstName + " " + lastName + " working in " + companyName + " is " + status)
    expect(companyName).toContain(cname)
    expect(firstName).toBe(fname)
    expect(lastName).toBe(lname)
    let pageTitle = await page.title()
    console.log("Page Title: " + pageTitle)
    expect(pageTitle).toBe("View Lead | opentaps CRM")
})

test("Edit Lead in Leaftaps", async ({ page }) => {
    await page.goto("https://leaftaps.com/opentaps/control/main")
    await page.getByRole("textbox", {name:"USERNAME"}).fill("democsr2")
    await page.getByRole("textbox", {name:"PASSWORD"}).fill("crmsfa")
    await page.getByRole("button", {name:"LOGIN"}).click()
    await page.locator('#label').click()
    await page.getByRole("link", {name:"Leads"}).click()
    await page.getByRole("link", {name:"Find Leads"}).click()
    let fname = "Naveen"
    await page.getByRole("textbox", {name:"First name"}).fill(fname)
    await page.getByRole("button", {name:"Find Leads"}).click()
    await page.locator('[class="linktext"]').nth(3).click()
    await page.getByRole("link", {name:"Edit"}).click()
    let cname2 = "Naveen Sugar clinic"
    await page.locator('#updateLeadForm_companyName').fill(cname2)
    await page.locator('#updateLeadForm_annualRevenue').fill("10,00,000 LPA")
    await page.locator("[name='departmentName']").fill("Diabetes")
    await page.locator('#updateLeadForm_description').fill("This is a Diabetes Clinic")
    await page.getByRole("button", {name:"Update"}).click()

    let companyName = await page.locator('#viewLead_companyName_sp').textContent()
    let annualRevenue = await page.locator('#viewLead_annualRevenue_sp').textContent()
    let department = await page.locator('#viewLead_departmentName_sp').textContent()

    expect(companyName).toContain(cname2)
    // expect(annualRevenue).toBe("$ 10,00,000.00")
    expect(annualRevenue).toMatch(/\$\s*10,00,000\.00/)
    expect(department).toMatch("Diabetes")
    console.log("The title of the page is : ", await page.title())
})

test("Create a new account in Salesforce", async ({ page }) => {
    await page.goto("https://login.salesforce.com/")
    let userID ="dilipkumar.rajendran@testleaf.com"
    let password = "TestLeaf@2025"
    await page.getByLabel("Username",{exact:true}).fill(userID)
    await page.getByLabel("Password",{exact:true}).fill(password)
    await page.getByRole("button", {name:"Log In"}).click()
    await page.waitForTimeout(6000)
    await page.waitForLoadState("domcontentloaded")
    let pageURL = page.url()
    console.log("The URL of the page is : ", pageURL)
    expect(page.url()).toContain("https://testleaf.lightning.force.com/lightning/page/home")
    console.log("The title of the page is : ", await page.title())
    expect(await page.title()).toBe("Home | Salesforce")
    await page.locator('[class="slds-icon-waffle"]').click()
    await page.locator('[aria-label="View All Applications"]').click(); //doubt how to get that locator using the GetByText Method?
    await page.getByPlaceholder("Search apps or items...").fill("Service")
    await page.locator('//p[@role="presentation"]').first().click()
    await page.locator('[title="Accounts"]').first().click()
    await page.getByRole("button", {name:"New"}).click()
    await page.locator('[name="Name"]').fill("TestLeaf")
    await page.locator('//button[@name="SaveEdit"]').click()
    await expect(page.locator("//span[contains(.,'was created')]")).toBeVisible()
})