import { test, expect } from "@playwright/test";

test('Handle Checkboxes', async ({ page }) => {

    await page.goto("https://leafground.com/checkbox.xhtml")
    await page.locator('//span[text()="Basic"]').click()
    await page.locator('//span[text()="Ajax"]').click()
    await expect(page.locator('//span[text()="Checked"]')).toBeVisible()
    await page.locator('//label[text()="Python"]').click()
    await page.locator('//label[text()="Javascript"]').click()
    await page.locator('div.ui-chkbox-box.ui-widget').nth(7).click()
    await expect(page.locator('//span[text()="State has been changed."]')).toBeVisible()
    let State = await page.locator('//span[text()="State has been changed."]/following::p').innerText()
    console.log("The State is : " + State)
    await page.locator('.ui-toggleswitch-slider').click()
    await page.locator('.ui-toggleswitch-slider').click()
    let toggleState = await page.locator('.ui-growl-title').textContent()
    console.log("The Toggle State is : " + toggleState)
    await expect.soft(page.locator('[class="ui-chkbox-label ui-state-disabled"]')).toBeDisabled()
    console.log("The Checkbox is Disabled")
    await page.locator('[data-label="Cities"]').click()
    await page.locator('//label[text()="Barcelona"]').last().click()
    await page.locator('//label[text()="Miami"]').last().click()
    await page.locator('//label[text()="Paris"]').last().click()
    await page.waitForTimeout(3000)
    await page.close()
})