import { expect, test } from "@playwright/test";
test("Playwright locators", async ({ page }) => {
    await page.goto("https://leaftaps.com/opentaps/control/main")
    await page.getByRole("textbox", {name:"USERNAME"}).fill("democsr2")
    await page.getByRole("textbox", {name:"PASSWORD"}).fill("crmsfa")
    await page.getByRole("button", {name:"LOGIN"}).click()
    await page.locator('#label').click()
    await page.getByRole("link", {name:"Leads"}).click()
    await page.getByRole("link", {name:"Create Lead"}).click()
    let cname = "Geetha Pathology Lab"
    let fname = "Naveen"
    let lname = "K"
    await page.locator('#createLeadForm_companyName').fill(cname)
    await page.locator('#createLeadForm_firstName').fill(fname)
    await page.locator('#createLeadForm_lastName').fill(lname)
    await page.locator('//input[@name="personalTitle"]').fill("Mr. ")
    await page.locator('//input[@name="generalProfTitle"]').fill("MBBS")
    await page.locator("#createLeadForm_departmentName").fill("Pathology")
    await page.locator('[id="createLeadForm_annualRevenue"]').fill("15,00,000 LPA")
    await page.locator('#createLeadForm_primaryPhoneCountryCode').fill("+91")
    await page.locator('#createLeadForm_primaryPhoneNumber').fill("9876543210")
    await page.getByRole("button", {name:"Create Lead"}).click()
    let companyName = await page.locator('#viewLead_companyName_sp').textContent()
    let firstName = await page.locator('#viewLead_firstName_sp').textContent()
    let lastName = await page.locator('#viewLead_lastName_sp').textContent()
    let status = await page.locator('#viewLead_statusId_sp').textContent()
    console.log("Company Name: " + companyName)
    console.log("First Name: " + firstName)
    console.log("Last Name: " + lastName)
    console.log("Status: " + status)
    console.log("The Status of the Lead Mr. " + firstName + " " + lastName + " working in " + companyName + " is " + status)
    expect(companyName).toContain(cname)
    expect(firstName).toBe(fname)
    expect(lastName).toBe(lname)
    let pageTitle = await page.title()
    console.log("Page Title: " + pageTitle)
})